import type { ModelDetail } from "@/lib/model-catalog/types";

export const fallbackModelCatalog: ModelDetail[] = [
  {
    id: "google/gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    description: "高效的多模态 Gemini 模型。",
    labId: "google",
    labName: "Google",
    family: "gemini-flash",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image", "audio", "video", "pdf"],
    outputModalities: ["text"],
    minInputPrice: 0.3,
    minInputProviderId: "google",
    minInputProviderName: "Google",
    minOutputPrice: 2.5,
    minOutputProviderId: "google",
    minOutputProviderName: "Google",
    releaseDate: "2025-06-17",
    updatedDate: "2025-06-17",
    providerCount: 1,
    providerIds: ["google"],
    providerNames: ["Google"],
    active: true,
    origin: "models.dev",
    knowledge: "2025-01",
    openWeights: false,
    capabilities: {
      attachment: true,
      reasoning: true,
      toolCall: true,
      structuredOutput: true,
      temperature: true,
    },
    providers: [
      {
        providerId: "google",
        providerName: "Google",
        providerModelId: "gemini-2.5-flash",
        canonicalModelId: "google/gemini-2.5-flash",
        labName: "Google",
        context: 1048576,
        output: 65536,
        inputPrice: 0.3,
        outputPrice: 2.5,
        capabilities: {
          attachment: true,
          reasoning: true,
          toolCall: true,
          structuredOutput: true,
          temperature: true,
        },
        inputModalities: ["text", "image", "audio", "video", "pdf"],
        outputModalities: ["text"],
        sourceUrl: "https://models.dev/providers/google",
        origin: "models.dev",
      },
    ],
    catalogVersion: "development-fallback",
    sourceUrl: "https://github.com/anomalyco/models.dev",
  },
  {
    id: "deepseek/deepseek-v3.2",
    name: "DeepSeek V3.2",
    labId: "deepseek",
    labName: "DeepSeek",
    context: 163840,
    output: 65536,
    inputModalities: ["text"],
    outputModalities: ["text"],
    minInputPrice: 0.28,
    minInputProviderId: "deepseek",
    minInputProviderName: "DeepSeek",
    minOutputPrice: 0.42,
    minOutputProviderId: "deepseek",
    minOutputProviderName: "DeepSeek",
    releaseDate: "2025-12-01",
    updatedDate: "2025-12-01",
    providerCount: 1,
    providerIds: ["deepseek"],
    providerNames: ["DeepSeek"],
    active: true,
    origin: "models.dev",
    openWeights: true,
    capabilities: { reasoning: true, toolCall: true },
    providers: [
      {
        providerId: "deepseek",
        providerName: "DeepSeek",
        providerModelId: "deepseek-v3.2",
        canonicalModelId: "deepseek/deepseek-v3.2",
        labName: "DeepSeek",
        context: 163840,
        output: 65536,
        inputPrice: 0.28,
        outputPrice: 0.42,
        capabilities: { reasoning: true, toolCall: true },
        inputModalities: ["text"],
        outputModalities: ["text"],
        sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
        origin: "models.dev",
      },
    ],
    catalogVersion: "development-fallback",
    sourceUrl: "https://github.com/anomalyco/models.dev",
  },
  {
    id: "openai/gpt-5.2",
    name: "GPT-5.2",
    labId: "openai",
    labName: "OpenAI",
    context: 400000,
    output: 128000,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    minInputPrice: 1.75,
    minInputProviderId: "openai",
    minInputProviderName: "OpenAI",
    minOutputPrice: 14,
    minOutputProviderId: "openai",
    minOutputProviderName: "OpenAI",
    releaseDate: "2025-12-11",
    updatedDate: "2025-12-11",
    providerCount: 1,
    providerIds: ["openai"],
    providerNames: ["OpenAI"],
    active: true,
    origin: "models.dev",
    openWeights: false,
    capabilities: { reasoning: true, toolCall: true, structuredOutput: true },
    providers: [
      {
        providerId: "openai",
        providerName: "OpenAI",
        providerModelId: "gpt-5.2",
        canonicalModelId: "openai/gpt-5.2",
        labName: "OpenAI",
        context: 400000,
        output: 128000,
        inputPrice: 1.75,
        outputPrice: 14,
        capabilities: {
          reasoning: true,
          toolCall: true,
          structuredOutput: true,
        },
        inputModalities: ["text", "image"],
        outputModalities: ["text"],
        sourceUrl: "https://platform.openai.com/docs/pricing",
        origin: "models.dev",
      },
    ],
    catalogVersion: "development-fallback",
    sourceUrl: "https://github.com/anomalyco/models.dev",
  },
];
